# Generated by Django 3.2.5 on 2022-03-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_colect', models.IntegerField()),
                ('vol_storage', models.BigIntegerField()),
                ('integration', models.CharField(choices=[('SL_S_FW', 'SL_S_FW'), ('SL_S_FWS', 'SL_S_FWS'), ('SL_S_PD', 'SL_S_PD'), ('SL_S_PD+FWS', 'SL_S_PD+FWS'), ('SL_L_P', 'SL_L_P'), ('SL_L_PS', 'SL_L_PS'), ('SL_L_RF', 'SL_L_RF'), ('SL_L_S', 'SL_L_S')], max_length=15)),
                ('fluid', models.CharField(choices=[('steam', 'steam'), ('water', 'water'), ('oil', 'oil')], max_length=15)),
                ('dist_supply', models.IntegerField()),
                ('surface', models.CharField(choices=[('roof_concrete', 'cubierta de hormigón'), ('roof_sandwich', 'cubierta sandwich'), ('ground_paved', 'suelo asfaltado'), ('ground_unpaved', 'suelo no asfaltado')], max_length=30)),
                ('transport', models.CharField(choices=[('truck', 'camión'), ('ship', 'barco')], max_length=15)),
                ('distance', models.BigIntegerField()),
                ('pressure', models.IntegerField()),
                ('cost', models.BigIntegerField()),
                ('real_offer', models.BooleanField()),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Solar_field',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presupuesto.project')),
            ],
            bases=('presupuesto.project',),
        ),
    ]
