# Generated by Django 4.0.3 on 2022-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Proyecto', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Solar_field',
        ),
    ]
