# Generated by Django 4.0.3 on 2022-04-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_bop_project_name_delete_solar_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Of_Plant',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presupuesto.project')),
            ],
            bases=('presupuesto.project',),
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presupuesto.project')),
            ],
            bases=('presupuesto.project',),
        ),
        migrations.CreateModel(
            name='mobility',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presupuesto.project')),
            ],
            bases=('presupuesto.project',),
        ),
        migrations.CreateModel(
            name='Solar_field',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presupuesto.project')),
            ],
            bases=('presupuesto.project',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='presupuesto.project')),
            ],
            bases=('presupuesto.project',),
        ),
    ]
