# Generated by Django 4.0.3 on 2022-04-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_balance_of_plant_construction_mobility_solar_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bop_cost',
            field=models.BigIntegerField(default=232323),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='construction_cost',
            field=models.BigIntegerField(default=2323),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='mobility_cost',
            field=models.BigIntegerField(default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='solar_field_cost',
            field=models.BigIntegerField(default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='storage_cost',
            field=models.BigIntegerField(default=345),
            preserve_default=False,
        ),
    ]
